sudo: false
language: android
cache:
  directories:
    - $HOME/.gradle/caches/
android:
  components:
    - platform-tools
    - tools
    - build-tools-21.1.1
    - android-21
script:
  - ./gradlew check
